version: '3.8'

services:

  # Frontend React + Vite servido con Nginx
  frontend:
    image: ${ECR_REPO_URL_FRONTEND}:latest
    container_name: despachos-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - red-frontend

# Red interna del frontend
networks:
  red-frontend:
    driver: bridge
